- name: Downloading and installing public key.
  rpm_key:
    state: present
    key: "{{ gpg_key_logstash }}"

- name: Creeating a repository
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    owner: root
    group: root
    mode: 0777

- name: Updating repository.
  dnf:
    update_cache: yes

- name: Installing Logstash and its dependencies.
  dnf:
    name:
      - logstash
    state: latest

- name: Opening port
  shell: |
    sudo firewall-cmd --permanent --zone=public --add-port=9600/tcp
    sleep 10
    sudo firewall-cmd --reload
- name: stared and enabled logstash
  service:
    name: logstash
    state: restarted
    enabled: true
