- name: Downloading elastic search
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.3-x86_64.rpm
    dest: /tmp/elasticsearch-8.4.3-x86_64.rpm

- name: Installing elasticsearch
  yum:
    name: /tmp/elasticsearch-8.4.3-x86_64.rpm
    state: present

- name: changing cluster.name.
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#cluster.name: my-app'
    replace: 'cluster.name: Edem_cluster'

- name: Configuring node.name.
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#node.name: node-1'
    replace: 'node.name: node-1'

- name: Configuring network.host.
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#network.host: 192.168.0.1'
    replace: 'network.host: 192.168.56.101'

- name: Configuring http.port.
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#http.port: 9300'
    replace: 'http.port: 9300'

- name: Configuring network.host.
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'xpack.security.enabled: true'
    replace: 'xpack.security.enabled: false'

- name: Enabling elastic search service.
  service:
    name: elasticsearch
    enabled: yes

- name: service file.
  replace:
    path: /usr/lib/systemd/system/elasticsearch.service
    regexp: "TimeoutStartSec=75"
    replace: "TimeoutStartSec=300"

- name: Opening port.
  shell: |
    sudo firewall-cmd --permanent --zone=public --add-port=9200/tcp
    sleep 10
    sudo firewall-cmd --reload
- name: Enabling elastic search service.
  shell: |
    systemctl enable elasticsearch.service
    sleep 10
    systemctl start elasticsearch.service
